.TH ASCIITEX 1 "15 Jan 2010"
.SH NAME
asciiTeX_gui \- Equation ASCII renderer
.SH SYNOPSIS
.B asciiTeX_gui
.SH DESCRIPTION
.B asciiTeX
is an ASCII equation renderer released under the terms of the The GNU
General Public License. The program can generate ASCII-art representations of 
mathematical equations. You can use asciiTeX to quickly insert equations in 
e.g. e-mails, in comments in your source-code, etc. The syntax is similar to LaTex.
The asciiTeX_gui program provides an easy to use graphical user interface.

.SH USAGE
After running a graphical user interface apears with the following elements:
.br
.B Equation Input Field
.br
This is where you can edit your equation. See the asciiTeX manual for the syntax.

.B Equation Output Field
.br
This is where the ASCII rendering of the equation is displayed. In case of errors 
these will also be displayed here.

.B Generate button
.br
Create the ASCII renering of the equation in the input field and display in the 
output field

.B Line-width check button
.br
Turn on or off automatic line-breaking for long equations. This will cause 
asciiTeX to attempts to format the equation within the specified line width, 
i.e., asciiTeX will insert line breaks in order to format long equations over 
several lines.

.B Line-width
.br
Here you can set the maximum line-width in characters. 

.SH AUTHORS
Bart Pieters.br

.SH LICENSE
GNU GENERAL PUBLIC LICENSE Version 2

.SH VERSION
0.2

.SH SEE ALSO
.B asciiTeX(1)

